### ISSUE TITLE
Doesn't work now

### ISSUE THREAD

**Issue by Zonic1987** [mudachyo/TapSwap#2]
Working before perfectly, but now I have error. Can you help me? 
![111111](https://github.com/mudachyo/TapSwap/assets/171349529/9b242226-5ace-4ba5-8799-2326d70ddf51)

**Comment by mudachyo** [comment]
Go there app.tapswap.club , pass the captcha and restart the app.

**Comment by Zonic1987** [comment]
I passed capcta, restart app and any changes( 
Screenshot when I tried to go to app.tapsswap.club. Its just spinning all time
![22222](https://github.com/mudachyo/TapSwap/assets/171349529/80b3d02c-8467-4e7e-a22e-2824f2727622)

**Comment by mudachyo** [comment]
Wait for them to take down cloudflare.
