### ISSUE TITLE
Бусты и реклама

### ISSUE THREAD

**Issue by Gerik13** [mudachyo/TapSwap#8]
Возможно ли доработать чтобы кликер использовал бусты?
Кстати после того как используется 3 буста Taping Guru, бот предлагает посмотреть 15-ти секундную рекламу, после чего дает возможность использовать еще буст.
Было бы прекрасно, если бы скрипт умел просматривать рекламу и использовать дополнительные бусты :)

**Comment by mudachyo** [comment]
Возможно, но делать этого я не планирую
